/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/units/{unitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["updateUnit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/subscription-plans/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["deactivate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_2"];
        put: operations["updateProperty"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leases/{leaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_3"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll"];
        put?: never;
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/subscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_1"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_2"];
        put?: never;
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leases/{leaseId}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/{unitId}/vacant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markVacant"];
        trace?: never;
    };
    "/api/v1/units/{unitId}/occupied": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markOccupied"];
        trace?: never;
    };
    "/api/v1/units/{unitId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["archiveUnit"];
        trace?: never;
    };
    "/api/v1/units/{unitId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["activateUnit"];
        trace?: never;
    };
    "/api/v1/units/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/property/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/subscription-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/subscription-plans/code/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByStatus_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/owner/{ownerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUnitRequest: {
            unitNumber?: string;
            label?: string;
            floor?: string;
            rentAmount?: number;
            depositAmount?: number;
            description?: string;
        };
        ApiResponseUnitResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UnitResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        UnitResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            propertyId?: string;
            unitNumber?: string;
            label?: string;
            floor?: string;
            description?: string;
            rentAmount?: number;
            depositAmount?: number;
            status?: string;
            occupancyStatus?: string;
        };
        UpdatePropertyRequest: {
            name?: string;
            description?: string;
        };
        Address: {
            streetAddress?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
        };
        ApiResponsePropertyResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PropertyResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        GeoLocation: {
            latitude?: number;
            longitude?: number;
        };
        PropertyDimensions: {
            /** Format: double */
            totalArea?: number;
            /** Format: double */
            occupiedArea?: number;
            /** Format: int32 */
            unitCount?: number;
            fullyOccupied?: boolean;
        };
        PropertyResponse: {
            /** Format: uuid */
            propertyId?: string;
            /** Format: uuid */
            tenantId?: string;
            name?: string;
            /** @enum {string} */
            propertyType?: "APARTMENT" | "BEDSITTER" | "STUDIO" | "MAISONETTE" | "VILLA" | "COMMERCIAL" | "OFFICE" | "WAREHOUSE" | "HOSTEL" | "AIRBNB";
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "INACTIVE" | "UNDER_MAINTENANCE" | "ARCHIVED";
            /** @enum {string} */
            occupancyStatus?: "VACANT" | "PARTIALLY_OCCUPIED" | "FULLY_OCCUPIED";
            address?: components["schemas"]["Address"];
            geoLocation?: components["schemas"]["GeoLocation"];
            dimensions?: components["schemas"]["PropertyDimensions"];
            description?: string;
        };
        UpdateLeaseRequest: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            rentAmount: number;
            securityDeposit: number;
            lateFeeAmount: number;
            /** Format: int32 */
            gracePeriodDays: number;
            autoRenew: boolean;
        };
        ApiResponseLeaseResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaseResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        LeaseResponse: {
            /** Format: uuid */
            id?: string;
            leaseNumber?: string;
            /** Format: uuid */
            propertyId?: string;
            /** Format: uuid */
            unitId?: string;
            /** Format: uuid */
            tenantProfileId?: string;
            /** @enum {string} */
            leaseType?: "STANDARD" | "FIXED_TERM" | "MONTH_TO_MONTH";
            /** @enum {string} */
            billingCycle?: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            rentAmount?: number;
            securityDeposit?: number;
            lateFeeAmount?: number;
            /** Format: int32 */
            gracePeriodDays?: number;
            autoRenew?: boolean;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateUnitRequest: {
            /** Format: uuid */
            propertyId?: string;
            unitNumber?: string;
            label?: string;
            rentAmount?: number;
            description?: string;
        };
        SubscriptionPlanRequest: {
            code?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            billingCycle?: "MONTHLY" | "YEARLY";
            /** Format: int32 */
            maxProperties?: number;
            /** Format: int32 */
            maxUnits?: number;
            /** Format: int32 */
            maxUsers?: number;
            /** Format: int32 */
            maxStorageGb?: number;
            monthlyPrice?: number;
            yearlyPrice?: number;
        };
        SubscriptionPlanResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            billingCycle?: "MONTHLY" | "YEARLY";
            /** Format: int32 */
            maxProperties?: number;
            /** Format: int32 */
            maxUnits?: number;
            /** Format: int32 */
            maxUsers?: number;
            /** Format: int32 */
            maxStorageGb?: number;
            monthlyPrice?: number;
            yearlyPrice?: number;
            active?: boolean;
        };
        CreatePropertyRequest: {
            name?: string;
            /** @enum {string} */
            propertyType?: "APARTMENT" | "BEDSITTER" | "STUDIO" | "MAISONETTE" | "VILLA" | "COMMERCIAL" | "OFFICE" | "WAREHOUSE" | "HOSTEL" | "AIRBNB";
            description?: string;
            address?: components["schemas"]["Address"];
            geoLocation?: components["schemas"]["GeoLocation"];
            dimensions?: components["schemas"]["PropertyDimensions"];
        };
        CreateLeaseRequest: {
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            unitId: string;
            /** Format: uuid */
            tenantProfileId: string;
            leaseNumber: string;
            /** @enum {string} */
            leaseType: "FIXED_TERM" | "MONTHLY";
            /** @enum {string} */
            billingCycle: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            rentAmount: number;
            securityDeposit: number;
            lateFeeAmount: number;
            /** Format: int32 */
            gracePeriodDays: number;
            autoRenew: boolean;
        };
        LeaseActionRequest: {
            /** Format: uuid */
            performedBy: string;
            /** @enum {string} */
            action: "APPROVE" | "ACTIVATE" | "TERMINATE" | "REJECT" | "RENEW";
            /** Format: date */
            actionDate?: string;
            /** @enum {string} */
            terminationType?: "TENANT_REQUEST" | "LANDLORD_REQUEST" | "BREACH_OF_CONTRACT" | "NON_PAYMENT" | "MUTUAL_AGREEMENT";
            reason?: string;
            actor?: string;
            reasonValid?: boolean;
            terminationValid?: boolean;
        };
        ApiResponseLeaseActionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaseActionResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        LeaseActionResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            previousStatus?: "DRAFT" | "PENDING_APPROVAL" | "ACTIVE" | "TERMINATED" | "REJECTED" | "EXPIRED" | "RENEWED";
            /** @enum {string} */
            currentStatus?: "DRAFT" | "PENDING_APPROVAL" | "ACTIVE" | "TERMINATED" | "REJECTED" | "EXPIRED" | "RENEWED";
            message?: string;
        };
        RegisterRequest: {
            email?: string;
            password?: string;
            /** Format: uuid */
            tenantId?: string;
        };
        MessageResponse: {
            message?: string;
        };
        LoginRequest: {
            email?: string;
            password?: string;
            /** Format: uuid */
            tenantId?: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        CreateTenantRequest: {
            tenantCode?: string;
            name?: string;
            slug?: string;
            email?: string;
            phoneNumber?: string;
            /** @enum {string} */
            tenantType?: "TRIAL" | "STANDARD" | "PREMIUM" | "ENTERPRISE";
            /** @enum {string} */
            subscriptionStatus?: "TRIAL" | "ACTIVE" | "LAPSED" | "CANCELLED" | "PAST_DUE" | "GRACE_PERIOD";
        };
        ApiResponseTenantResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TenantResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        TenantResponse: {
            /** Format: uuid */
            tenantId?: string;
            name?: string;
            email?: string;
            phoneNumber?: string;
            address?: string;
            status?: string;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageUnitResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageUnitResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        PageUnitResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["UnitResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"][];
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
            paged?: boolean;
            unpaged?: boolean;
        };
        SortObject: {
            direction?: string;
            nullHandling?: string;
            ascending?: boolean;
            property?: string;
            ignoreCase?: boolean;
        };
        ApiResponsePagePropertyResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PagePropertyResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        PagePropertyResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["PropertyResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        ApiResponseListPropertyResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PropertyResponse"][];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        ApiResponseLeaseDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaseDetailResponse"];
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
        LeaseDetailResponse: {
            /** Format: uuid */
            id?: string;
            leaseNumber?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            propertyId?: string;
            /** Format: uuid */
            unitId?: string;
            /** @enum {string} */
            leaseType?: "FIXED_TERM" | "MONTHLY";
            /** @enum {string} */
            billingCycle?: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            rentAmount?: number;
            securityDeposit?: number;
            /** @enum {string} */
            status?: "DRAFT" | "PENDING_APPROVAL" | "ACTIVE" | "TERMINATED" | "REJECTED" | "EXPIRED" | "RENEWED";
            /** Format: int32 */
            gracePeriodDays?: number;
            autoRenew?: boolean;
            /** Format: date */
            createdAt?: string;
            /** Format: date */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
            errorCode?: string;
            /** Format: int64 */
            timestamp?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUnitResponse"];
                };
            };
        };
    };
    updateUnit: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUnitResponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePropertyResponse"];
                };
            };
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePropertyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePropertyResponse"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaseDetailResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaseResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageUnitResponse"];
                };
            };
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUnitResponse"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionPlanResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionPlanResponse"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagePropertyResponse"];
                };
            };
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePropertyResponse"];
                };
            };
        };
    };
    archiveProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePropertyResponse"];
                };
            };
        };
    };
    activateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePropertyResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaseResponse"];
                };
            };
        };
    };
    action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaseActionResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTenantResponse"];
                };
            };
        };
    };
    markVacant: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                "X-Correlation-Id"?: string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    markOccupied: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                "X-Correlation-Id"?: string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    archiveUnit: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    activateUnit: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                "X-Correlation-Id"?: string;
            };
            path: {
                unitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getByStatus: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageUnitResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                keyword?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageUnitResponse"];
                };
            };
        };
    };
    getByProperty: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header: {
                "X-Tenant-Id": string;
            };
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageUnitResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionPlanResponse"];
                };
            };
        };
    };
    getByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionPlanResponse"];
                };
            };
        };
    };
    getByStatus_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPropertyResponse"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query: {
                keyword?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagePropertyResponse"];
                };
            };
        };
    };
    getByOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPropertyResponse"];
                };
            };
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTenantResponse"];
                };
            };
        };
    };
}
